import { ArrowRight, Building2, Landmark, Map, ScanSearch } from 'lucide-react'
import '../../styles/LandingPage.css'
import './LandingOverride.css'

export function LandingPage({ onNavigate }: { onNavigate: (page: string) => void }) {
  const cards = [
    { title: 'AI-Driven Valuation', body: 'Harness machine learning to predict property market values with unprecedented accuracy, analyzing thousands of historical data points instantly.', page: 'Property Valuation', icon: <ScanSearch size={19}/> },
    { title: 'GIS Mapping Integration', body: 'Visualize municipal land assets with real-time interactive mapping and parcel tracking. Layer zoning, flood plains, and assessment data.', page: 'GIS Map', icon: <Map size={19}/> },
    { title: 'Ownership Lifecycle', body: 'Seamlessly manage ownership transfers, tax declarations, and historical property records in a secure, immutable ledger.', page: 'Ownership Transfer', icon: <Building2 size={19}/> },
  ]
  return <div className="lp-root"><header className="lp-header"><button className="lp-brand" onClick={() => onNavigate('Landing')}><Landmark className="lp-logo"/><span><span className="lp-brand-name">Assessor Pro AI</span><span className="lp-brand-sub">City Hall District</span></span></button><nav className="lp-nav"><button onClick={() => document.getElementById('tools')?.scrollIntoView({ behavior: 'smooth' })}>Features</button><button onClick={() => document.getElementById('tools')?.scrollIntoView({ behavior: 'smooth' })}>Solutions</button><button className="lp-signin" onClick={() => onNavigate('Dashboard')}>Sign In</button></nav></header>
    <main><section className="lp-hero"><div className="lp-hero-left"><span className="lp-badge">✦ AI-Powered Valuation Engine</span><h1>Modernizing Municipal<br/>Property Assessment with<br/>AI</h1><p className="lp-lead">A comprehensive records management and GIS mapping system designed for the next generation of city assessors. Ensure accuracy, transparency, and efficiency.</p><div className="lp-cta"><button className="lp-primary" onClick={() => onNavigate('Dashboard')}>Get Started <ArrowRight size={16}/></button><button className="lp-outline" onClick={() => document.getElementById('tools')?.scrollIntoView({ behavior: 'smooth' })}>Explore Features</button></div></div><div className="lp-hero-right"><div className="lp-image-stack"><div className="lp-image"/><div className="lp-image"/></div></div></section>
    <section className="lp-stats"><button className="lp-stat" onClick={() => onNavigate('Lot Management')}>12,000+<br/><span className="lp-stat-label">Properties Managed</span></button><button className="lp-stat" onClick={() => onNavigate('Property Valuation')}>98%<br/><span className="lp-stat-label">AI Prediction Accuracy</span></button><button className="lp-stat" onClick={() => onNavigate('Dashboard')}>15+<br/><span className="lp-stat-label">Municipal Districts Supported</span></button></section>
    <section id="tools" className="lp-cards"><h2>Comprehensive Assessor Tools</h2><p>Built specifically for municipal needs, combining traditional records management with<br/>advanced analytics.</p><div className="lp-card-grid">{cards.map(card => <article className="lp-card" key={card.title}><div className="lp-card-icon">{card.icon}</div><div className="lp-card-title">{card.title}</div><p className="lp-card-body">{card.body}</p><button className="lp-card-link" onClick={() => onNavigate(card.page)}>{card.title === 'GIS Mapping Integration' ? 'Explore maps' : card.title === 'Ownership Lifecycle' ? 'View workflows' : 'Learn more'} <ArrowRight size={13}/></button></article>)}</div></section></main>
    <footer className="lp-footer"><div><strong>Assessor Pro AI</strong><p>City Hall District · Department of Municipal Assessment</p></div><div className="lp-footer-links"><button onClick={() => onNavigate('Dashboard')}>Dashboard</button><button onClick={() => onNavigate('Reports')}>Reports</button><button onClick={() => onNavigate('Ownership Transfer')}>Support</button></div></footer>
  </div>
}
