import { Building2, ClipboardCheck, Sparkles, MapPin } from 'lucide-react'
import { properties } from '../data/properties'
import { PropertyTable } from '../components/common/PropertyTable'
import type { EstimateInput } from '../types/property'
const peso = (value: number) => `₱${new Intl.NumberFormat('en-PH').format(value)}`
export function AiValuationView({ value, onChange }: { value: EstimateInput; onChange: (value: EstimateInput) => void }) {
  const estimate = Math.round((Number(value.lot) * 1250 + Number(value.building) * 18500) * Math.max(.65, 1 - Number(value.age) * .008)); const confidence = Math.min(94, 78 + (Number(value.building) > 0 ? 8 : 0))
  return <><div className="title-row"><div><p className="eyebrow">AI-ASSISTED ASSESSMENT</p><h1>Property Value Estimation</h1><p className="subhead">Use comparable records and property details to support your assessment decision.</p></div><span className="ai-chip"><Sparkles size={15}/> Comparable Value Model v1</span></div><div className="valuation-grid"><section className="card estimate-form"><h2>Property details</h2><p>Enter the information available for this property.</p><div className="form-grid"><label>Property type<select value={value.type} onChange={e => onChange({...value, type:e.target.value})}><option>Residential</option><option>Commercial</option><option>Agricultural</option></select></label><label>Building age<input type="number" value={value.age} onChange={e => onChange({...value, age:e.target.value})}/></label><label>Lot area (sqm)<input type="number" value={value.lot} onChange={e => onChange({...value, lot:e.target.value})}/></label><label>Building area (sqm)<input type="number" value={value.building} onChange={e => onChange({...value, building:e.target.value})}/></label><label>Classification<select><option>{value.type}</option><option>Industrial</option></select></label><label>Nearby facilities<select><option>Schools, road, commercial</option><option>Road access only</option></select></label></div><button className="primary full"><Sparkles size={17}/> Generate estimate</button></section><section className="card estimate-result"><div className="result-top"><div><p className="eyebrow">RECOMMENDED MARKET VALUE</p><h2>{peso(estimate)}</h2><span>Suggested assessed value: <strong>{peso(Math.round(estimate * .2))}</strong></span></div><div className="confidence"><strong>{confidence}%</strong><span>confidence</span></div></div><div className="confidence-bar"><i style={{width: `${confidence}%`}}/></div><Factor icon={<Building2/>} title="Comparable properties" detail="4 nearby residential records analyzed"/><Factor icon={<MapPin/>} title="Location and access" detail="Near local road, school, and commercial area"/><Factor icon={<ClipboardCheck/>} title="Assessment level" detail="20% residential assessment level applied"/><p className="explanation">This estimate considers the recorded property characteristics and recent comparable values. Review the recommendation before approving it.</p><div className="result-actions"><button className="outline">Edit value</button><button className="primary">Approve estimate</button></div></section></div><section className="card comparable"><div className="card-head"><div><h2>Similar properties used</h2><p>Recent records used to support this prediction</p></div><button className="text-button">View all comparisons</button></div><PropertyTable rows={properties.slice(0,3)}/></section></>
}
function Factor({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="factor">{icon}<div><strong>{title}</strong><span>{detail}</span></div></div> }
