import { useState } from 'react'
import type { FormEvent } from 'react'
import { ArrowRight, Building2, Eye, EyeOff, Landmark, LockKeyhole, Mail } from 'lucide-react'
import api from '../lib/api'
import '../styles/AuthPages.css'

function Shell({ children, register = false }: { children: React.ReactNode; register?: boolean }) { return <main className={`auth-page ${register ? 'auth-register' : ''}`}><section className="auth-card"><div className="auth-panel"><div className="auth-brand"><Landmark size={19}/><strong>Accessor Office</strong></div>{children}</div><aside className="auth-image"><div className="auth-image-copy">{register ? <><div className="stars">★★★★★</div><strong>“Accessor Office has completely transformed our municipal property valuation process. It brings stability, transparency, and increased accuracy to Lagonglong.”</strong><span>Lagonglong Municipal Assessor<br/>Lagonglong, Misamis Oriental</span></> : <><Building2 size={21}/><h2>Accessor Office</h2><p>Supporting fair and accurate property valuation in Lagonglong, Misamis Oriental.</p></>}</div></aside></section></main> }

export function LoginPage({ onNavigate }: { onNavigate: (page: string) => void }) { const [username, setUsername] = useState('admin'), [password, setPassword] = useState('password'), [show, setShow] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false); const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { const { data } = await api.post('/login', { username, password }); localStorage.setItem('accessor_token', data.token); onNavigate('Dashboard') } catch (err: any) { setError(err.response?.data?.message || 'Unable to sign in. Check that the API server is running.') } finally { setBusy(false) } }; return <Shell><form className="auth-form" onSubmit={submit}><div className="auth-heading"><h1>Welcome Back</h1><p>Please enter your credentials to access the assessor portal.</p></div>{error && <p className="auth-error">{error}</p>}<label>Email address or username<div className="auth-input"><Mail size={15}/><input value={username} onChange={e => setUsername(e.target.value)} autoComplete="username" required/></div></label><label>Password<div className="auth-input"><LockKeyhole size={15}/><input type={show ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" required/><button type="button" onClick={() => setShow(!show)}>{show ? <EyeOff size={15}/> : <Eye size={15}/>}</button></div></label><label className="auth-check"><input type="checkbox"/> Remember this device for 30 days</label><button className="auth-submit" disabled={busy}>{busy ? 'Signing in…' : <>Sign In <ArrowRight size={16}/></>}</button><p className="auth-switch">No account yet? <button type="button" onClick={() => onNavigate('Register')}>Register</button></p><footer>Secure Access System for City Hall Staff.<br/>© 2024 Municipal Solutions Group.</footer></form></Shell> }

export function RegisterPage({ onNavigate }: { onNavigate: (page: string) => void }) { const [form, setForm] = useState({ first_name: '', last_name: '', username: '', email: '', password: '' }), [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false); const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { const { data } = await api.post('/register', form); setMessage(data.message); setTimeout(() => onNavigate('Login'), 900) } catch (err: any) { setError(err.response?.data?.message || 'Unable to create your account.') } finally { setBusy(false) } }; const set = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value }); return <Shell register><form className="auth-form" onSubmit={submit}><div className="auth-heading"><h1>Create an account</h1><p>Register for official municipal access. All fields are required.</p></div>{error && <p className="auth-error">{error}</p>}{message && <p className="auth-success">{message}</p>}<label>Full name<div className="auth-two"><input placeholder="First name" value={form.first_name} onChange={e => set('first_name', e.target.value)} required/><input placeholder="Last name" value={form.last_name} onChange={e => set('last_name', e.target.value)} required/></div></label><label>Municipal email<div className="auth-input"><Mail size={15}/><input type="email" placeholder="name@municipality.gov" value={form.email} onChange={e => set('email', e.target.value)} required/></div></label><label>Username<input className="auth-plain" placeholder="e.g. jdoe" value={form.username} onChange={e => set('username', e.target.value)} required/></label><label>Password<input className="auth-plain" type="password" minLength={6} value={form.password} onChange={e => set('password', e.target.value)} required/></label><button className="auth-submit" disabled={busy}>{busy ? 'Creating…' : <>Create Account <ArrowRight size={16}/></>}</button><p className="auth-switch">Already have an account? <button type="button" onClick={() => onNavigate('Login')}>Sign In</button></p><footer>© 2024 Municipal Assessor’s Office · Privacy Policy · Terms of Service</footer></form></Shell> }
