import { Bot, Building2, MapPin, Plus, Sparkles, Users } from 'lucide-react'
import { Metric } from '../common/Metric'
import { PropertyTable } from '../common/PropertyTable'
import { SearchBox } from '../common/SearchBox'
import type { Property } from '../../types/property'

function Activity({ initials, color, text, name }: { initials: string; color: string; text: string; name: string }) { return <div className="activity-row"><div className={`person ${color}`}>{initials}</div><div><strong>{text}</strong><span>{name}</span></div></div> }
export function DashboardView({ active, query, onQueryChange, rows, onNavigate, onRegister }: { active: string; query: string; onQueryChange: (value: string) => void; rows: Property[]; onNavigate: (page: string) => void; onRegister: () => void }) {
  const isDashboard = active === 'Dashboard'
  return <><div className="title-row"><div><p className="eyebrow">WELCOME BACK, ADMIN</p><h1>{isDashboard ? 'Dashboard Overview' : active}</h1><p className="subhead">{isDashboard ? "Here's what's happening with your records today." : `Manage ${active.toLowerCase()} in one place.`}</p></div><button className="primary" onClick={onRegister}><Plus size={18}/> Register Property</button></div><div className="metrics"><Metric icon={<Building2/>} title="Total Properties" value="2,847" detail="12 added this month" color="blue"/><Metric icon={<Users/>} title="Property Owners" value="1,926" detail="8 new owners this month" color="violet"/><Metric icon={<Sparkles/>} title="AI Estimates" value="86" detail="94% average confidence" color="orange"/><Metric icon={<MapPin/>} title="Mapped Properties" value="2,114" detail="74% with GPS location" color="green"/></div><div className="dashboard-grid"><section className="card records"><div className="card-head"><div><h2>Recent Property Records</h2><p>Latest property registrations and updates</p></div><button className="text-button" onClick={() => onNavigate('Property Records')}>View all →</button></div><SearchBox value={query} onChange={onQueryChange}/><PropertyTable rows={rows}/></section><aside className="side-column"><section className="card activity"><div className="card-head"><div><h2>Recent Activity</h2><p>Latest system updates</p></div></div><Activity initials="AI" color="violet" text="AI estimate generated" name="TD-2024-01842 · 12 minutes ago"/><Activity initials="JD" color="blue" text="Assessment updated" name="Jose R. Dela Cruz · 1 hour ago"/><Activity initials="AR" color="purple" text="Tax declaration generated" name="Ana P. Reyes · 3 hours ago"/><button className="outline">View all activity</button></section><section className="quick"><div><h3>Quick Actions</h3><p>Common tasks at your fingertips</p></div><button onClick={() => onNavigate('AI Valuation')}><Bot size={18}/><span>Generate AI estimate</span></button><button onClick={() => onNavigate('GIS Map')}><MapPin size={18}/><span>Browse property map</span></button><button onClick={onRegister}><Plus size={18}/><span>Register a new property</span></button></section></aside></div></>
}
